const list_product = [
     
    // Điện thoại Apple
    {
        id: 3,
        masp: "#125",
        tensp: "iPhone 13",
        hinhanh: "/assets/DienThoai/iPhone13.png",
        trangthai: "Điện thoại",
        gia: "8.500.000",
    },
    {
        id: 4,
        masp: "#126",
        tensp: "iPhone 12 Pro",
        hinhanh: "/assets/DienThoai/iPhone12Pro.png",
        trangthai: "Điện thoại",
        gia: "9.200.000",
    },
    {
        id: 5,
        masp: "#127",
        tensp: "iPhone SE",
        hinhanh: "/assets/DienThoai/iPhoneSE.png",
        trangthai: "Điện thoại",
        gia: "6.500.000",
    },
    {
        id: 6,
        masp: "#128",
        tensp: "iPhone 11",
        hinhanh: "/assets/DienThoai/iPhone11.png",
        trangthai: "Điện thoại",
        gia: "7.800.000",
    },
    {
        id: 7,
        masp: "#129",
        tensp: "iPhone XR",
        hinhanh: "/assets/DienThoai/iPhoneXR.png",
        trangthai: "Điện thoại",
        gia: "5.000.000",
    },
    // AirPods
    {
        id: 8,
        masp: "#130",
        tensp: "AirPods Pro",
        hinhanh: "",
        trangthai: "Tai nghe",
        gia: "2.500.000",
    },
    {
        id: 9,
        masp: "#131",
        tensp: "AirPods 2nd Gen",
        hinhanh: "",
        trangthai: "Tai nghe",
        gia: "1.800.000",
    },
    {
        id: 10,
        masp: "#132",
        tensp: "AirPods Max",
        hinhanh: "",
        trangthai: "Tai nghe",
        gia: "5.000.000",
    },
    {
        id: 11,
        masp: "#133",
        tensp: "AirPods 3rd Gen",
        hinhanh: "",
        trangthai: "Tai nghe",
        gia: "2.200.000",
    },
    {
        id: 12,
        masp: "#134",
        tensp: "AirPods Pro 2nd Gen",
        hinhanh: "",
        trangthai: "Tai nghe",
        gia: "2.800.000",
    },
    // Apple Watch
    {
        id: 13,
        masp: "#135",
        tensp: "Apple Watch Series 7",
        hinhanh: "",
        trangthai: "Đồng hồ thông minh",
        gia: "9.000.000",
    },
    {
        id: 14,
        masp: "#136",
        tensp: "Apple Watch SE",
        hinhanh: "",
        trangthai: "Đồng hồ thông minh",
        gia: "6.500.000",
    },
    {
        id: 15,
        masp: "#137",
        tensp: "Apple Watch Series 6",
        hinhanh: "",
        trangthai: "Đồng hồ thông minh",
        gia: "7.800.000",
    },
    {
        id: 16,
        masp: "#138",
        tensp: "Apple Watch Series 5",
        hinhanh: "",
        trangthai: "Đồng hồ thông minh",
        gia: "7.200.000",
    },
    {
        id: 17,
        masp: "#139",
        tensp: "Apple Watch Series 4",
        hinhanh: "",
        trangthai: "Đồng hồ thông minh",
        gia: "6.000.000",
    },
];